In [2]:
import pandas as pd

In [3]:
pd.__version__

'0.23.0'

In [5]:
pd.read_excel('DB_Auszug_ROTCE_und_RSE_nachBsp2_CU38088 - Kopie.xlsx')

,,ACCOUNT_NUMBER,CLASS_ID,CUSTOMER_NUMBER,DETAIL_DELETION_INDICATOR,END_EFFECTIVE_DATE,EVENT_CREATION_TEMPLATE_ID,EVENT_UNIQUE_ID,FILE_RECORD_SEQUENCE_NUMBER,FILE_SEQUENCE_NUMBER,...,SOURCE_INFO_NULL_INDICATOR,CUSTOMER_CLASSIFICATION,BUNDLE_PACKET_ID,GUIDING_DATE,ACCESS_NUMBER_ID,SKELETON_CONTRACT_NUMBER,SITE_ID,GENERIC_INFO_1,GENERIC_INFO_2,CHARGE_OCCURRENCE_TYPE
0,1,700076501,6049,710074951,*,2021-12-31,bC34.N2KF7ulQKGG,1350890000000001,1,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
1,2,700076501,6049,710074951,*,2021-12-31,bC44KN2KF7ulQKGG,1350890000000002,2,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
2,3,700076501,6050,710074951,*,2021-12-01,bC44WN2KF7ulQKGG,1350890000000003,3,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
3,4,700076501,6049,710074951,*,2021-12-31,Gi084JW5CfGqvDT8,1350890000000004,4,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
4,5,700076501,6050,710074951,*,2021-12-01,Gi083JW5CfGqvDT8,1350890000000005,5,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
5,6,700076501,6049,710074951,*,2021-12-31,Gi081JW5ClGqvDT8,1350890000000006,6,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
6,7,700076501,6049,710074951,*,2021-12-31,Gi082JW5CiGqvDT8,1350890000000007,7,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
7,8,700076501,6049,710074951,*,2021-12-31,Gi081JW576GmvDT8,1350890000000008,8,135089,...,0,VE,NaN,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
8,9,700076501,6050,710074951,*,2021-12-01,Gi080JW576GmvDT8,1350890000000009,9,135089,...,0,VE,NaN,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
9,10,700076501,6049,710074951,*,2021-12-31,Gi082JW5CmGqvDT8,1350890000000010,10,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN
10,11,700076501,6049,710074951,*,2021-12-31,Gi084JW5CiGqvDT8,1350890000000011,11,135089,...,0,VE,VY1SaXcrCn0ZvAB9,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN